# Execution target: local | sauce
execution.env=local

# Local Appium
appium.server.url=http://127.0.0.1:4723
android.platformVersion=16.0
android.deviceName=Pixel_8
android.appPath=apps/mda-2.2.0-25.apk
android.appPackage=com.saucelabs.mydemoapp.android
android.appActivity=com.saucelabs.mydemoapp.android.view.activities.SplashActivity
android.automationName=UiAutomator2
android.noReset=false

# SauceLabs (set SAUCE_USERNAME / SAUCE_ACCESS_KEY as env vars, never hardcode)
sauce.region=eu-central-1
sauce.app.storage=storage:filename=mda-2.2.0-25.apk
sauce.device.name=Google Pixel 8.*
sauce.device.platformVersion=14.*
sauce.build=levelup-mobile-1.0

# App under test users (My Demo App defaults)
std.user=bod@example.com
std.password=10203040
locked.user=alice@example.com
locked.password=10203040

# Backend API (My Demo App has no public API -> use PracticeSoftwareTesting API for BE track)
api.base.url=https://api.practicesoftwaretesting.com
api.user.email=customer@practicesoftwaretesting.com
api.user.password=welcome01

# Timeouts
explicit.wait.seconds=15
